#!/bin/sh

### BEGIN INIT INFO
# Provides:        gpio
# Required-Start:  $network $remote_fs $syslog
# Required-Stop:   $network $remote_fs $syslog
# Default-Start:   2 3 4 5
# Default-Stop: 
# Short-Description: Start GPIO daemon
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin

. /lib/lsb/init-functions

DAEMON=/usr/local/sbin/gpiod
NAME=gpiod

test -x $DAEMON || exit 5

RUNASUSER=root
UGID=$(getent passwd $RUNASUSER | cut -f 3,4 -d:) || true

case $1 in
	start)
		log_daemon_msg "Starting GPIO server" "gpiod"
		if [ -z "$UGID" ]; then
			log_failure_msg "user \"$RUNASUSER\" does not exist"
			exit 1
		fi
  		start-stop-daemon --start --quiet --oknodo --startas $DAEMON --exec $DAEMON -- 
		status=$?
		log_end_msg $status
  		;;
	stop)
		log_daemon_msg "Stopping GPIO server" "gpiod"
  		start-stop-daemon --stop --quiet --oknodo --signal HUP --name $NAME
		log_end_msg $?
  		;;
	restart|force-reload)
		$0 stop && sleep 2 && $0 start
  		;;
	try-restart)
		if $0 status >/dev/null; then
			$0 restart
		else
			exit 0
		fi
		;;
	reload)
		exit 3
		;;
	status)
		status_of_proc $DAEMON "GPIO server"
		;;
	*)
		echo "Usage: $0 {start|stop|restart|try-restart|force-reload|status}"
		exit 2
		;;
esac
